# Generated by Django 5.2.12 on 2026-04-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_pass_percentage_result_passed_result_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='correct_marks',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='exam',
            name='wrong_marks',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(),
        ),
    ]
