# Generated by Django 5.2.12 on 2026-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_correct_marks_exam_wrong_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('written', 'Written')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='written_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultanswer',
            name='written_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resultanswer',
            name='selected_option',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
