# Generated by Django 5.2.12 on 2026-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_result_review_pending_resultanswer_awarded_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
