# Generated by Django 5.2.12 on 2026-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_instructions_exam_max_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Exam Portal', max_length=200)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('certificate_title', models.CharField(default='Certificate of Achievement', max_length=200)),
                ('default_pass_percentage', models.FloatField(default=40.0)),
            ],
            options={
                'verbose_name': 'Portal Settings',
                'verbose_name_plural': 'Portal Settings',
            },
        ),
    ]
